### ISSUE TITLE
Remove or improve padding for const/let/var

### ISSUE THREAD

**Issue by timseverien** [vicompany/eslint-config-vi#21]
[The config currently forces padding after `const`s, `let`s and `var`s](https://github.com/vicompany/eslint-config-vi/blob/master/config/defaults.js#L201-L202).

Although I get the sentiment of separating assignments, it removes the freedom to decide what grouping is best per use-case. I often run into this when dealing with the DOM API.

## Examples

This is a simple example that honours 8.0.0, but requires several context switches.

```js
const canvas = document.createElement('canvas');
const container = document.createElement('div');

// Switch mental context to canvas
canvas.classList.add('my-canvas-class');

// Switch mental context to container
container.classList.append('my-container-class');
container.appendChild(canvas);
```

This is the same code but grouped by subject. It removes the need to switch context, but the whitespace feels excessive.

```js
const canvas = document.createElement('canvas');

canvas.classList.add('my-canvas-class');

const container = document.createElement('div');

container.classList.append('my-container-class');

container.appendChild(canvas);
```

## Solution

By either adding nuance or removing the variable declaration padding, developers get the freedom to choose how to group code.

```js
const canvas = document.createElement('canvas');
canvas.classList.add('my-canvas-class');

const container = document.createElement('div');
container.classList.append('my-container-class');

container.appendChild(canvas);
```

**Comment by ba55ie** [comment]
This doesn't seem possible with ESLint, at least without disabling the rule. Isn't DOM scripting somewhat of an edge case, which can be solved in other ways?

```javascript
someNode.insertAdjacentHTML('beforeend', '<div class="my-container-class"><canvas class="my-canvas-class"></canvas></div>');
```

**Comment by timseverien** [comment]
The above examples can indeed be fixed other ways. A better example would have been using APIs that _cannot_ be defined in a HTML fragment, like `HTMLElement.addEventListener(...)`.

**Comment by pimskie** [comment]
Currently not relevant anymore. Checked it, and once it becomes relevant again, a PR will be created
