### ISSUE TITLE
Disable / Change max line length property

### ISSUE THREAD

**Issue by svensigmond** [vicompany/eslint-config-vi#26]
80 characters is too little in many cases and forces us to write code in a different way solely for a linter.

There also seems to be buggy behaviour where some short lines are marked as too long, while lines that are too long pass the validation.

**Comment by ba55ie** [comment]
I'll have to investigate a little further. It seems that `Standard` also doesn't enforce a line-length, but it still is a good practice. The bugs are fixed by the way.

**Comment by ba55ie** [comment]
## Other configs

- [ESLint: 80](https://eslint.org/docs/rules/max-len) (default)
- [Airbnb: 100](https://github.com/airbnb/javascript/blob/master/packages/eslint-config-airbnb-base/rules/style.js#L195)
- Standard: none
- [Prettier: 80](https://prettier.io/docs/en/options.html#print-width) (converts code to this length)

## History and info
- https://softwareengineering.stackexchange.com/questions/148677/why-is-80-characters-the-standard-limit-for-code-width
- http://richarddingwall.name/2008/05/31/is-the-80-character-line-limit-still-relevant/
