### ISSUE TITLE
Change array destructuring error to warning

### ISSUE THREAD

**Issue by svensigmond** [vicompany/eslint-config-vi#27]
In some cases array destructuring leads to verbose code. There is currently no way to circumvent using destructuring, except manually disabling it through the use of a comment.

Changing this rule from an error to a warning would give us more flexibility in this matter.

**Comment by timseverien** [comment]
This applies to object destructuring as well.

**Comment by ba55ie** [comment]
@svensigmond It's been a while, but do you have an example? :)
Destructuring often results in less verbose code and you get the benefits of renaming variables and default values.

**Comment by ba55ie** [comment]
Thanks! Returning warnings seems legit.
