### ISSUE TITLE
Unexpected token on spread operator

### ISSUE THREAD

**Issue by sjorsjes** [vicompany/eslint-config-vi#29]
const obj1 = {};
    const obj2 = {};
    const combinedObjects = { ...obj1 , ...obj2 };

Gives the following error: `[eslint] Parsing error: Unexpected token ...`

**Comment by timseverien** [comment]
ESLint doesn't support object rest spread by default. Until the setting below is added to `eslint-config-vi`, you can add it to the `.eslintrc` of your project:

```json
"parserOptions": {
  "ecmaFeatures": {
    "experimentalObjectRestSpread": true
  }
}
```

**Comment by ba55ie** [comment]
Object Rest/Spread Properties are a part of ES2018 which is finalized a couple of days ago. When [ESLint supports it](https://github.com/eslint/eslint/issues/9885), we can update the ECMA version.

- https://github.com/tc39/proposals/blob/master/finished-proposals.md
- http://2ality.com/2017/02/ecmascript-2018.html
- http://kangax.github.io/compat-table/es2016plus/#test-object_rest/spread_properties

**Comment by ba55ie** [comment]
We can update the ECMA version to 2018 and use object destructuring! https://eslint.org/docs/user-guide/configuring#deprecated
