### ISSUE TITLE
Warning unexpected confirm

### ISSUE THREAD

**Issue by sjorsjes** [vicompany/eslint-config-vi#6]
We might want to allow [native confirms](https://developer.mozilla.org/en-US/docs/Web/API/Window/confirm)?

![confirm](https://cloud.githubusercontent.com/assets/2182172/14530887/42e5f4ca-025b-11e6-9422-8c8881fe2ce0.jpg)

**Comment by ba55ie** [comment]
The [no alert rule](http://eslint.org/docs/rules/no-alert) is quite sane, so I would override it just the project and not globally.
