### ISSUE TITLE
Create a new major release for ESLint 7.0.x

### ISSUE THREAD

**Issue by ba55ie** [vicompany/eslint-config-vi#64]
See https://eslint.org/blog/2020/02/whats-coming-in-eslint-7.0.0

Some nodejs/commonjs rules will be deprecated (in the near future) and put into a separate config, so we have to decide what to do with our node.js config.

**Comment by ba55ie** [comment]
I created a branch `next` for development on this: 66ae538

**Comment by ba55ie** [comment]
Migration guide (to be merged into `master` of ESLint): https://github.com/eslint/eslint/blob/migrating-guide-7/docs/user-guide/migrating-to-7.0.0.md

**Comment by ba55ie** [comment]
https://eslint.org/blog/2020/05/eslint-v7.0.0-released

**Comment by pimskie** [comment]
The current package is now based on eslint 7.

**Comment by ba55ie** [comment]
Finally 😎
